### ISSUE TITLE
Error message upon sending a "test" email: Sending failed. Reason:: Emailaddress "" is not valid according to RFC 2822 standards

### ISSUE THREAD

**Issue by dkingsjr** [anoved/OctoPrint-EmailNotifier#46]
i keep getting the error message in the title when attempting to send a test email. It is frustrating, as i figured this plugin was relatively "plug-n-play".

**Comment by ericli1018** [comment]
please use my fork under your topic, I fixed those issue.

**Comment by dkingsjr** [comment]
with all due respect, i am unsure of that claim. but then again, If this plug in requires a better understanding of how to use python, and navigating the terminal in PI, i am not to that point. I un installed and then re-installed the plug in, and i still get the same issues.

**Comment by anoved** [comment]
Hi @dkingsjr. Sorry for the difficulty. Unfortunately I am not able to maintain this plugin. In its current state it is definitely not plug-n-play. I have not tried @ericli1018's fixes, but they are likely to be your best bet at the moment. (Thanks @ericli1018!)

**Comment by Stady234** [comment]
you need to add the following to your "keyring"
yagmail.SMTP(user='emailaccount')

I just completed this on 0.15.1...
